name: Backend And Frontend AWS push
on: 
    push:
        branches:
            - main

jobs:
    docker-push:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: List All items in root
              run: ls -a
            - name: Run docker compose in the root directory
              run: docker compose up -d
            - name: Check docker files
             run: docker ps -a

