name: Backend Docker Push
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: List files in the root directory
              run: ls -a
            - name: Install NPM dependencies in the backend directory
              run: |
                cd backend
                ls -a
                npm i
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Run docker compose in the backend directory
              run: |
                cd backend
                docker compose up