name: Run Tests
on: push
#   pull_request:
#     branches:
#       - master

jobs:
    trivy_scan:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3

            - name: List files in the root directory
              run: ls -a

            - name: Install Trivy
              run: |
                sudo apt-get install -y wget apt-transport-https
                wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
                sudo dpkg -i trivy_0.34.0_Linux-64bit.deb

            - name: docker images up
              run: docker compose up -d
            - name: run trivy test
              run: |
                trivy image emp-backend:latest
                trivy image nginx:latest

    forntend-test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3

            - name: List files in the root directory
              run: ls -a

            - name: Install eslint
              run: |
                cd frontend
                sudo apt-get install -y npm
                npm install -g eslint
                npm install eslint-plugin-react eslint-plugin-react-hooks --save-dev
            
            - name: run eslint test
              run: |
                npx eslint --init
                npm run lint
                npm run lint:fix

            - name: run audit
              run: |
                npm audit
                npm audit fix

